"$schema" = "./node_modules/wrangler/config-schema.json"

# Cloudflare Pages configuration
name = "profile"
compatibility_date = "2025-10-10"
compatibility_flags = ["nodejs_compat"]

# For SvelteKit adapter-cloudflare
pages_build_output_dir = ".svelte-kit/cloudflare"